// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {domain} from '../models';

export function AbortPTT():Promise<void>;

export function FinalTranscript(arg1:string,arg2:string,arg3:string):Promise<void>;

export function GetRuntimeInfo():Promise<Record<string, string>>;

export function GetStatus():Promise<domain.Status>;

export function PartialTranscript(arg1:string):Promise<void>;

export function SessionError(arg1:domain.ErrorCode,arg2:string):Promise<void>;

export function SessionStateChanged(arg1:domain.SessionState,arg2:domain.SessionStateReason):Promise<void>;

export function StartPTT():Promise<domain.Status>;

export function StopPTT():Promise<domain.StopResult>;
