// @ts-check
// This file is automatically generated. DO NOT EDIT

export function AbortPTT() {
    return window['go']['main']['App']['AbortPTT']();
}

export function GetRuntimeInfo() {
    return window['go']['main']['App']['GetRuntimeInfo']();
}

export function GetStatus() {
    return window['go']['main']['App']['GetStatus']();
}

export function StartPTT() {
    return window['go']['main']['App']['StartPTT']();
}

export function StopPTT() {
    return window['go']['main']['App']['StopPTT']();
}
