// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AbortPTT() {
  return window['go']['main']['App']['AbortPTT']();
}

export function FinalTranscript(arg1, arg2, arg3) {
  return window['go']['main']['App']['FinalTranscript'](arg1, arg2, arg3);
}

export function GetRuntimeInfo() {
  return window['go']['main']['App']['GetRuntimeInfo']();
}

export function GetStatus() {
  return window['go']['main']['App']['GetStatus']();
}

export function PartialTranscript(arg1) {
  return window['go']['main']['App']['PartialTranscript'](arg1);
}

export function SessionError(arg1, arg2) {
  return window['go']['main']['App']['SessionError'](arg1, arg2);
}

export function SessionStateChanged(arg1, arg2) {
  return window['go']['main']['App']['SessionStateChanged'](arg1, arg2);
}

export function StartPTT() {
  return window['go']['main']['App']['StartPTT']();
}

export function StopPTT() {
  return window['go']['main']['App']['StopPTT']();
}
