// This file is automatically generated. DO NOT EDIT

export function AbortPTT(): Promise<void>;
export function GetRuntimeInfo(): Promise<{ [key: string]: string }>;
export function GetStatus(): Promise<{ state: string; active: boolean; message?: string }>;
export function StartPTT(): Promise<{ state: string; active: boolean; message?: string }>;
export function StopPTT(): Promise<{ rawTranscript: string; finalTranscript: string; copied: boolean }>;
